method : 'bayes'
name : 'FoundationModel_MAE_sweep'
metric :
  goal : 'minimize'
  name : 'val_MAE_loss'

parameters :
  BATCH_SIZE: 
    value: 64
  weight_decay :
    value : 2e-5 
    # distribution : 'normal'
    # mu : 5e-5
    # sigma : 1e-4
  lr : 
    value : 3.0e-4
    # distribution : 'normal'
    # mu : 3.0e-4
    # sigma : 1.0e-4
  scheduler_name: 
    value : 'cosine_decay_lr_scheduler'

  patch_size: 
    values : [4,8]
  num_classes: 
    value: 3 
  dim: 
    values : [64, 96]
  depth: 
    values : [3,4]
  heads:
    value: 4
  mlp_dim_ratio: 
    values: [1.5 , 2] 
  pool: 
    value: 'cls'
  channels: 
    value: 1
  dim_head: 
    values: [64, 96]
  dropout: 
    value: 0.1

  decoder_dim : 
    values: [64, 96] 
  masking_ratio: 
    values : [0.25, 0.5 , 0.75, 0.9]
  decoder_depth: 
    values : [1,2]
  decoder_heads: 
    value: 4
  decoder_dim_head: 
    value: 64