MAE_params:
  decoder_depth: ${sweep_config.decoder_depth}
  decoder_dim: ${sweep_config.decoder_dim}
  decoder_dim_head: ${sweep_config.decoder_dim_head}
  decoder_heads: ${sweep_config.decoder_heads}
  masking_ratio: ${sweep_config.masking_ratio}
ViT_params:
  channels: ${sweep_config.channels}
  depth: ${sweep_config.depth}
  dim: ${sweep_config.dim}
  dim_head: ${sweep_config.dim_head}
  dropout: ${sweep_config.dropout}
  heads: ${sweep_config.heads}
  image_size: 64
  mlp_dim_ratio: ${sweep_config.mlp_dim_ratio}
  num_classes: ${sweep_config.num_classes}
  patch_size: ${sweep_config.patch_size}
  pool: ${sweep_config.pool}
callbacks_config:
  EarlyStopping:
    min_delta: 5.0e-05
    mode: min
    monitor: val_MAE_loss
    patience: 5
    verbose: true
  ModelCheckpoint:
    mode: min
    monitor: val_MAE_loss
    save_last: true
    save_top_k: 1
    verbose: true
data_config:
  batch_size: ${train_config.BATCH_SIZE}
  num_workers: ${train_config.num_workers}
  tr_path: data/dataframes/foundation_models_pretraining_dataset/train_df.csv
  tst_path: data/dataframes/foundation_models_pretraining_dataset/test_df.csv
  val_path: data/dataframes/foundation_models_pretraining_dataset/val_df.csv
scheduler_params:
  cosine_decay_lr_scheduler_params:
    T_max: 250
    eta_min: 1.0e-07
  exponential_decay_lr_scheduler_params:
    gamma: 0.99
  scheduler_name: ${sweep_config.scheduler_name}
sweep_config:
  BATCH_SIZE: 64
  channels: 1
  decoder_depth: 2
  decoder_dim: 96
  decoder_dim_head: 64
  decoder_heads: 4
  depth: 4
  dim: 64
  dim_head: 96
  dropout: 0.1
  heads: 4
  lr: 0.0003
  masking_ratio: 0.5
  mlp_dim_ratio: 2
  num_classes: 3
  patch_size: 4
  pool: cls
  scheduler_name: cosine_decay_lr_scheduler
  weight_decay: 2.0e-05
train_config:
  BATCH_SIZE: ${sweep_config.BATCH_SIZE}
  MAX_EPOCHS: 200
  accelerator: gpu
  accumulate_grad_batches: 4
  ckpt_file_name: '{epoch} | {val_MAE_loss:.3f}'
  dataset_objective: pretraining
  dir: results/MAE
  lr: ${sweep_config.lr}
  model_name: MAE_ViT
  num_workers: 8
  weight_decay: ${sweep_config.weight_decay}
