ViT_params:
  image_size: 64
  patch_size: 4
  num_classes: 3 
  dim: 128
  depth: 4
  heads: 4
  mlp_dim_ratio: 3
  pool: 'cls' 
  channels: 1
  dim_head: 64
  dropout: 0.1


train_config:
  model_name: 'Task-4A_ViT' 
  dataset_objective : "finetuned_classification"
  BATCH_SIZE: 64
  weight_decay : 0.0001
  lr : 5.0e-6
  ckpt_file_name : '{epoch} | {val_ce_loss:.3f}'
  dir : "results/MAE"
  accumulate_grad_batches : 3
  accelerator : 'gpu'
  MAX_EPOCHS : 100
  num_workers: 8
  pretrained_mae_ckpt_path: 'results/MAE/MAE_ViT_pretraining/ckpts/epoch=119 | val_MAE_loss=0.010.ckpt'
  find_unused_parameters : False

data_config:
  tr_path: "data/dataframes/foundation_models_classification_dataset/train_df.csv"
  val_path : "data/dataframes/foundation_models_classification_dataset/val_df.csv"
  tst_path : "data/dataframes/foundation_models_classification_dataset/test_df.csv"
  batch_size : ${train_config.BATCH_SIZE}
  num_workers : ${train_config.num_workers}
  objective : ${train_config.dataset_objective}

scheduler_params:
  scheduler_name: 'cosine_decay_lr_scheduler'

  cosine_decay_lr_scheduler_params:
    T_max: 150
    eta_min: 1.0e-07

  exponential_decay_lr_scheduler_params:
    gamma: 0.99

callbacks_config:
  ModelCheckpoint:
    monitor: 'val_ce_loss'
    mode: 'min'
    save_top_k: 1
    save_last: True
    verbose : True
  EarlyStopping:
    monitor: 'val_ce_loss'
    mode: 'min'
    min_delta : 0.00005
    patience : 8
    verbose : True
