ViT_params:
  image_size: 150
  patch_size: 16
  num_classes: 3 
  dim: 64
  depth: 3
  heads: 4
  mlp_dim_ratio: 1.2
  pool: 'cls' 
  channels: 1
  dim_head: 64
  dropout: 0.

MAE_params:
  decoder_dim : 64
  masking_ratio: 0.75
  decoder_depth: 1
  decoder_heads: 8
  decoder_dim_head: 64


train_config:
  model_name: "MAE_ViT"
  dataset_objective : "pretraining"
  BATCH_SIZE: 4
  weight_decay : 0.0001
  lr : 0.1
  ckpt_file_name : '{epoch} | {val_MAE_loss:.3f}'
  dir : "results/MAE"
  accumulate_grad_batches : 5
  accelerator : cpu
  MAX_EPOCHS : 1
  num_workers: 8
  log_images_every_n_epochs : 5

data_config:
  tr_path: "data/dataframes/foundation_models_pretraining_dataset/train_df.csv"
  val_path : "data/dataframes/foundation_models_pretraining_dataset/val_df.csv"
  tst_path : "data/dataframes/foundation_models_pretraining_dataset/test_df.csv"
  batch_size : ${train_config.BATCH_SIZE}
  num_workers : ${train_config.num_workers}

scheduler_params:
  scheduler_name: 'cosine_decay_lr_scheduler'

  cosine_decay_lr_scheduler_params:
  T_max: 250
  eta_min: 1.0e-07

  exponential_decay_lr_scheduler_params:
    gamma: 0.99

callbacks_config:
  ModelCheckpoint:
    monitor: 'val_MAE_loss'
    mode: 'min'
    save_top_k: 1
    save_last: True
    verbose : True
  EarlyStopping:
    monitor: 'val_MAE_Loss'
    mode: 'min'
    min_delta : 0.00005
    patience : 8
    verbose : True