GaussianDiffusion_params:
  auto_normalize: true
  beta_schedule: ${sweep_config.beta_schedule}
  ddim_sampling_eta: 0.4
  image_size: 152
  immiscible: false
  min_snr_gamma: ${sweep_config.min_snr_gamma}
  min_snr_loss_weight: false
  objective: ${sweep_config.objective}
  offset_noise_strength: 0.0
  sampling_timesteps: null
  schedule_fn_kwargs: ${noise_scheduler_params.${sweep_config.beta_schedule}}
  timesteps: ${sweep_config.timesteps}
UNet_params:
  attn_dim_head: ${sweep_config.attn_dim_head}
  attn_heads: ${sweep_config.attn_heads}
  channels: 1
  dim: ${sweep_config.dim}
  dim_mults: ${sweep_config.dim_mults}
  dropout: ${sweep_config.dropout}
  flash_attn: ${sweep_config.flash_attn}
  full_attn: null
  init_dim: ${sweep_config.init_dim}
  learned_sinusoidal_cond: ${sweep_config.learned_sinusoidal_cond}
  learned_sinusoidal_dim: ${sweep_config.learned_sinusoidal_dim}
  learned_variance: ${sweep_config.learned_variance}
  out_dim: ${sweep_config.out_dim}
  random_fourier_features: ${sweep_config.random_fourier_features}
  self_condition: false
  sinusoidal_pos_emb_theta: ${sweep_config.sinusoidal_pos_emb_theta}
callbacks_config:
  EarlyStopping:
    min_delta: 5.0e-05
    mode: min
    monitor: val_MSE_loss
    patience: 5
    verbose: true
  ModelCheckpoint:
    mode: min
    monitor: val_MSE_loss
    save_last: true
    save_top_k: 1
    verbose: true
data_config:
  BATCH_SIZE: ${train_config.BATCH_SIZE}
  num_workers: ${train_config.num_workers}
  test_path: data/dataframes/diffusion_dataset/test_df.csv
  train_path: data/dataframes/diffusion_dataset/train_df.csv
  val_path: data/dataframes/diffusion_dataset/val_df.csv
noise_scheduler_params:
  cosine:
    s: 0.008
  sigmoid:
    clamp_min: 1e-5
    end: 3
    start: -3
    tau: 1
scheduler_params:
  cosine_decay_lr_scheduler_params:
    T_max: 200
    eta_min: 1.0e-07
  exponential_decay_lr_scheduler_params:
    gamma: 0.99
  scheduler_name: ${sweep_config.scheduler_name}
sweep_config:
  BATCH_SIZE: 8
  attn_dim_head: 32
  attn_heads: 4
  beta_schedule: sigmoid
  dim: 128
  dim_mults:
  - 1
  - 2
  - 3
  - 4
  dropout: 0.15
  flash_attn: false
  init_dim: 32
  learned_sinusoidal_cond: false
  learned_sinusoidal_dim: 32
  learned_variance: false
  lr: 0.0003
  min_snr_gamma: 3
  objective: pred_v
  out_dim: 1
  random_fourier_features: false
  scheduler_name: cosine_decay_lr_scheduler
  sinusoidal_pos_emb_theta: 10000
  timesteps: 100
  weight_decay: 1.0e-05
train_config:
  BATCH_SIZE: ${sweep_config.BATCH_SIZE}
  MAX_EPOCHS: 100
  accelerator: gpu
  accumulate_grad_batches: 8
  ckpt_file_name: '{epoch} | {val_MSE_loss:.3f}'
  dir: results/Diffusion
  log_images_every_n_epochs: 5
  loss_lambda: 10
  lr: ${sweep_config.lr}
  model_name: Vanilla_Gaussian_Diffusion
  num_workers: 8
  should_log_images: false
  weight_decay: ${sweep_config.weight_decay}
