method : 'bayes'
name : 'DiffusionModel_sweep'
metric :
  goal : 'minimize'
  name : 'val_MSE_loss'

parameters :
  BATCH_SIZE : 
    value : 8
  weight_decay :
    value: 0.00001
    # distribution : 'normal'
    # mu : 5e-5
    # sigma : 1e-4
  lr :
    value : 3e-4
    # distribution : 'normal'
    # mu : 3e-4
    # sigma : 1e-4
  scheduler_name : 
    value : 'cosine_decay_lr_scheduler'

  # gaussian diffusion specific parameters
  timesteps : 
    values : [50, 100]
  objective : 
    value : 'pred_v'
  beta_schedule : 
    values : ['sigmoid', 'cosine']
  min_snr_gamma : 
    values : [3,5]

  # Unet specific parameters
  dim : 
    values : [64, 96, 128]
  init_dim : 
    value : 32
  out_dim : 
    value : 1
  dim_mults : 
    value : [1, 2, 3, 4]
  learned_variance : 
    value : False
  learned_sinusoidal_cond : 
    value : False
  random_fourier_features : 
    value : False
  learned_sinusoidal_dim : 
    value : 32
  sinusoidal_pos_emb_theta : 
    value : 10000
  dropout : 
    value : 0.15
  attn_dim_head : 
    value : 32
  attn_heads : 
    value : 4
  flash_attn : 
    value : False
