train_config:
  model_name: "Vanilla_Gaussian_Diffusion"
  BATCH_SIZE: 16
  weight_decay : 0.0001
  lr : 2e-4
  ckpt_file_name : '{epoch} | {val_MSE_loss:.3f}'
  dir : "results/Diffusion"
  accumulate_grad_batches : 8
  accelerator : gpu
  MAX_EPOCHS : 100
  num_workers: 8
  should_log_images : !!bool True
  log_images_every_n_epochs : 5

data_config:
  train_path: 'data/dataframes/diffusion_dataset/train_df.csv'
  val_path: 'data/dataframes/diffusion_dataset/val_df.csv'
  test_path: 'data/dataframes/diffusion_dataset/test_df.csv'
  BATCH_SIZE : ${train_config.BATCH_SIZE}
  num_workers : ${train_config.num_workers}

scheduler_params:
  scheduler_name: 'cosine_decay_lr_scheduler'

  cosine_decay_lr_scheduler_params:
    T_max: 250
    eta_min: 1.0e-07

  exponential_decay_lr_scheduler_params:
    gamma: 0.99

noise_scheduler_params:
  cosine:
    s : 0.008
  sigmoid:
    start : -3
    end : 3
    tau : 1
    clamp_min : 1e-5

GaussianDiffusion_params:
  image_size: 152
  timesteps: 100
  sampling_timesteps: null
  objective: 'pred_v'
  beta_schedule : 'sigmoid'
  schedule_fn_kwargs : ${noise_scheduler_params.${GaussianDiffusion_params.beta_schedule}}
  ddim_sampling_eta : 0.4
  auto_normalize : True
  offset_noise_strength : 0.  
  min_snr_loss_weight : True
  min_snr_gamma : 3
  immiscible : False

UNet_params:
  dim : 128
  init_dim : 32
  out_dim : 1
  dim_mults : [1, 2, 3, 4]
  channels : 1
  self_condition : False    # In self-conditioning, network uses its own previous prediction as an additional input in subsequent denoising steps.
  learned_variance : False
  learned_sinusoidal_cond : False
  random_fourier_features : False
  learned_sinusoidal_dim : 32
  sinusoidal_pos_emb_theta : 10000 
  dropout : 0.15
  attn_dim_head : 32
  attn_heads : 4
  full_attn : null    # defaults to full attention only for inner most layer
  flash_attn : False



callbacks_config:
  ModelCheckpoint:
    monitor: 'val_MSE_loss'
    mode: 'min'
    save_top_k: 1
    save_last: True
    verbose : True
  EarlyStopping:
    monitor: 'val_MSE_Loss'
    mode: 'min'
    min_delta : 0.00005
    patience : 8
    verbose : True
